import Head from "next/head";

function Heading({
  title = "Mehmet YILDIZ | Front End Developer",
  description = "Generated by create next app",
}) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      <meta charSet="utf-8" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    </Head>
  );
}

export default Heading;
