import React from "react";
import Image from "../node_modules/next/image";
import Head from "../node_modules/next/head";

function blog() {
  return (
    <>
      <Head>
        <title>Mehmet YILDIZ | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        className=" z-10"
        layout="fill"
        objectFit="cover"
        src="/assets/ist.jpg"
        alt="/"
      />
      <h2 className="absolute top-[85%] left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-20 text-center text-shadow">
        I am revamping the site and going to add my blog soon.
      </h2>
    </>
  );
}

export default blog;
